### ISSUE TITLE
Notification通知提醒框

### ISSUE THREAD

**Issue by xiexingen** [nomui/nomui#101]
# Notification通知提醒框
全局展示通知提醒信息。

## 何时使用
在系统四个角显示通知提醒信息。经常用于以下情况：
- 较为复杂的通知内容
- 带有交互的通知，给出用户下一步的行动点
- 系统主动推送

**Comment by jerry-nom** [comment]
打算 Popup 用第三方组件 popper js 实现。然后 layer 修改成针对某个容器定位，然后 Notification 再继承自 layer。
