### ISSUE TITLE
Grid组件缓存排序问题

### ISSUE THREAD

**Issue by xiaocun0202** [nomui/nomui#1043]
columnsCustomizable 属性有 selected 值时候：
步骤：
1.点击排序，此时会显示排序图标 “向上” 或 “向下” 。
2.刷新页面，排序图标没了，鼠标移动上去显示为 “上下”  图标。

参考代码：
var fn_grid_cache = function () {
        let grid1 = null
        const mydata = [
            { id: 1, name: '笑傲江湖', author: '金庸', sales: 100000, role: '令狐冲' },
            { id: 4, name: '天龙八部', author: '金庸', sales: 200000, role: '乔峰' },
            { id: 5, name: '射雕英雄传', author: '金庸', sales: 80000, role: '郭靖' },
        ]
        const cols = [{
            field: 'name',
            key: 'name',
            title: '标题',
            width: 200,
            sortable: true,
        },
        {
            field: 'author',
            key: 'author',
            title: '作者',
            sortable: true,
        },
        {
            field: 'sales',
            key: 'sales',
            title: '销量',
            sortable: (a, b) => b.sales - a.sales,
        },
        {
            field: 'role',
            key: 'role',
            title: '主角',
            width: 500,
        },
        ]
        const defaultCols = [{
            field: 'name',
            key: 'name',
            title: '标题',
            width: 200,
            sortable: true,
        },
        {
                field: 'sales',
                key: 'sales',
                title: '销量',
                sortable: (a, b) => b.sales - a.sales,
            },
        ]
        return {
            component: 'Grid',
            ref: (c) => {
               grid1 = c
            },
            key: 'grid-demo-sort',
            sortCacheable: true,
            columnResizable: {
                cache: true,
            },
            allowFrozenCols: true,
            columns: cols,
            columnsCustomizable: {
                cache: 'grid-demo-sort-List',
                selected: defaultCols, //这里注释后正常
            },
            data: mydata,
        }
    }

![image](https://user-images.githubusercontent.com/11991250/233966824-c26f0dfe-fccf-4927-b7d6-9331ef4949f5.png)
![image](https://user-images.githubusercontent.com/11991250/233966877-4acb7aac-d3bc-42ad-9b3d-78fd5343b208.png)
![image](https://user-images.githubusercontent.com/11991250/233967048-3f79d506-ceb1-4ca4-ba71-08890754910a.png)

**Comment by fatalisa** [comment]
这种情况外部调用Grid实例的saveSortInfo(null)方法可以重置排序状态。
