### ISSUE TITLE
Layer 组件需要支持设置 offset

### ISSUE THREAD

**Issue by xiexingen** [nomui/nomui#1084]
背景：目前可以通过 alignTo、alignOuter 来设置 Layer 的位置，但是某些场景下需要对弹窗的 Layer层进行微调，比如距离本来的位置偏移多少像素
![image](https://github.com/nomui/nomui/assets/7939085/4343b362-b55b-41b3-a990-64f7d07a88c9)
比如: 这种情况想让 Layer 在原来的基础上往上 2px 
期望提供一个属性配置  : 
offset :{
  top: '', // 
  left: '',
}

ps: 可以评估下看是否有必要

**Comment by fatalisa** [comment]
已支持，用法如下 offset:[20,20], // [x轴,y轴]
