### ISSUE TITLE
Grid组件功能完善

### ISSUE THREAD

**Issue by fatalisa** [nomui/nomui#112]
- [x] Pager每页显示条数
- [x] 冻结表头 冻结列（sticky）
- [x] 排序 自定义排序函数
- [ ] 勾选 全选
- [x] 多级表头
- [ ] 列设置
- [x] 行合并 列合并
- [ ] hover效果
- [ ] stripe样式
- [ ] 列文字强制省略
- [ ] 拖拽改变列宽
- [ ] 列数据带children显示  展开折叠  嵌套子表格
- [ ] 加载完成自动滚动到某一行/某一列

**Comment by fatalisa** [comment]
hover效果
stripe样式

**Comment by fatalisa** [comment]
加载完成自动滚动到某一行/某一列

**Comment by fatalisa** [comment]
|  配置项   | 用途  | 类型  | 默认值  |
|  ----  | ----  |----  |----  |
| frozenHeader  | 冻结表头|boolean |false |
| frozenLeftCols  | 冻结左侧列|number|-|
| frozenRightCols  | 冻结右侧列|number|-|

**Comment by jerry-nom** [comment]
这个 api 感觉还不错
