### ISSUE TITLE
Grid:横向滚动条，表头和内容滚动不同步，导致错位。

### ISSUE THREAD

**Issue by mhymhygi** [nomui/nomui#120]
滚动前
![image](https://user-images.githubusercontent.com/12321689/111409458-ef111500-8711-11eb-94c1-fb251809f319.png)
滚动后
![image](https://user-images.githubusercontent.com/12321689/111409440-e8829d80-8711-11eb-9a89-baeab752cbf4.png)

**Comment by fatalisa** [comment]
用到自定义render的时候，需要设置一个宽度，保证列宽大于render返回内容的宽度，否则就会造成header跟body的scrollWidth不一致从而导致无法滚动
