### ISSUE TITLE
CheckboxList 多选情况下，赋值不能是数组，只能单个赋值

### ISSUE THREAD

**Issue by fatalisa** [nomui/nomui#257]
多选的时候，取值是一个数组，但是赋值用这个数组无效，字符串形式也无效，只能单个赋值
![image](https://user-images.githubusercontent.com/40448732/119590490-6e545080-be07-11eb-9fbb-24d3f3c9679c.png)

**Comment by xiexingen** [comment]
@NaivetyEvil  这个你跟踪下

**Comment by NaivetyEvil** [comment]
已解决
