### ISSUE TITLE
Grid 调整当前页面默认显示数据条数时，页面显示为空的情况 feature

### ISSUE THREAD

**Issue by chensuifeng** [nomui/nomui#300]
![image](https://user-images.githubusercontent.com/24535400/120969939-52549580-c79d-11eb-86b0-74c0e4d26264.png)
![image](https://user-images.githubusercontent.com/24535400/120970194-af504b80-c79d-11eb-8bf0-10acaf19483b.png)

**Comment by xiexingen** [comment]
@jerry-nom  @fatalisa  打算这样吧，切换页码直接回到第一页
