### ISSUE TITLE
tabs页面 加载route   bug

### ISSUE THREAD

**Issue by chensuifeng** [nomui/nomui#317]
![image](https://user-images.githubusercontent.com/24535400/121664863-83550300-cada-11eb-8e11-76791a05214e.png)
这个多个页签加载route时，通过nomapp.currentRoute.push传递参数；在第三次切换tab以后，每次获取到的参数是上一次的参数
![image](https://user-images.githubusercontent.com/24535400/121665056-b6979200-cada-11eb-8110-b29216a66bf2.png)

**Comment by fatalisa** [comment]
已解决，非组件问题
