### ISSUE TITLE
DateRangePicker  控件只读属性没效果

### ISSUE THREAD

**Issue by timgarnett** [nomui/nomui#523]
{
              component: 'DateRangePicker',
              name: 'timeRange',
              label: '发生时段',
                span: 12,
                readonly: true,
              required: true,
              format: 'yyyy-MM-dd',
              fieldName: {
                start: 'startTime',
                end: 'endTime',
              },
              value: viewValue,
            },

**Comment by Huzhangjie** [comment]
组件不提供 `readonly`属性，需要不可编辑的话，使用 `disabled` 吧
