### ISSUE TITLE
新插件 ，下拉选择 。树形带tab带查询框，如图

### ISSUE THREAD

**Issue by LL129** [nomui/nomui#581]
![image](https://user-images.githubusercontent.com/95060249/143514708-d9b6fe15-44f5-4b41-b7ff-3c92e7440d79.png)
![image](https://user-images.githubusercontent.com/95060249/143514752-79293b77-c292-44e7-bdbe-dd5d1a04de1e.png)
![image](https://user-images.githubusercontent.com/95060249/143514785-f0d9edb8-95ff-4d15-8e3c-936ea0576a2f.png)

**Comment by jerry-nom** [comment]
这个属于业务组件了
