### ISSUE TITLE
Grid使用功能扩展

### ISSUE THREAD

**Issue by alisa0318** [nomui/nomui#602]
1，树形表格加上排序，点击排序之后不会显示树形形态，子节点也不呈现了。
![image](https://user-images.githubusercontent.com/12756440/145660240-458a55a8-696d-4aac-89fe-b08ae4844cf6.png)

2，是否提供根据业务数据设置默认行样式，还是根据cellRender自己去设置。
3，表格汇总行支持。跟随主体滚动。如下图。
![image](https://user-images.githubusercontent.com/12756440/145660238-a82e33f3-1fbb-495f-ba77-db1d8a5bd46c.png)

**Comment by Huzhangjie** [comment]
1.排序后导致重复将扁平数据组装成树结构的操作（已解决）
3.已添加表尾合计行的配置 `summary`，详情见[示例](https://nomui.wetrial.org/#/components/demo?type=Grid&demo=summary)
