### ISSUE TITLE
组件库统一代码风格（样式以及配置项）

### ISSUE THREAD

**Issue by fatalisa** [nomui/nomui#679]
每个组件都要优化，涉及两个工作：1 所有用到的样式改为使用css变量，不再使用绝对值；  2 组件配置全部改为静态属性，参考Grid组件

基础：
- [x] Button
- [x] Icon

布局：
- [x] Layout
- [x] Container
- [x] Flex
- [x] Panel
- [x] Divider

导航
- [x] Menu
- [x] Dropdown
- [x] Toolbar
- [x] Navbar
- [x] Tabs
- [x] Pager
- [x] Collapse
- [x] Breadcrumb

浮层
- [x] Layer
- [x] Popup
- [x] Popconfirm
- [x] Modal
- [x] Drawer
- [x] Alert
- [x] Confirm
- [x] Message
- [x] Notification
- [x] Tooltip
- [x] Loading

数据展示:
- [x] Avatar
- [x] AvatarGroup
- [x] Badge
- [x] Timeline
- [x] List
- [x] Tag
- [x] Tree
- [x] Table
- [x] Grid
- [x] Statistic
- [x] Countdown
- [x] Carousel

数据录入
- [x] Textbox
- [x] Password
- [x] MultilineTextbox
- [x] Numberbox
- [x] NumberSpinner
- [x] Checkbox
- [x] Radiolist
- [x] CheckboxList
- [x] CheckboxTree
- [x] Select
- [x] Cascader
- [x] TreeSelect
- [x] AutoComplete
- [x] Transfer
- [x] TimePicker
- [x] TimeRangePicker
- [x] DatePicker
- [x] DateRangePicker
- [x] PartialDatePicker
- [x] PartialDateRangePicker
- [x] Uploader
- [x] Rate
- [x] Slider
- [x] StaticText
- [x] MaskInfo
- [x] Field
- [x] Group
- [x] GroupList
- [x] GroupGrid
- [x] Form

反馈
- [x] Progress
- [x] Spinner
- [x] Empty
- [x] Result
- [x] Steps

其他
- [x] Skeleton
- [x] Caption
- [x] Ellipsis
- [x] SlideCaptcha
- [x] Anchor
- [x] BackTop

**Comment by luoquan1982** [comment]
1、Breadcrumb
2、Drawer
3、Statistic
4、Countdown
5、NumberSpinner
6、Switch
7、Cascader
8、AutoComplete
9、Uploader
10、Steps

**Comment by Huzhangjie** [comment]
1. Progress

**Comment by Huzhangjie** [comment]
1. Progress
2. Spinner
3. Empty
4. Result
5. Skeleton
6. Caption
7. Ellipsis
8. SlideCaptcha
9. Anchor
10. BackTop
