### ISSUE TITLE
弹出层动画在其他组件使用时的效果优化

### ISSUE THREAD

**Issue by jerry-nom** [nomui/nomui#775]
现在实现的弹出层动画使用在其他组件里效果不合适，例如下拉框的动画等，需要调整为适合组件的动画效果。

**Comment by Edison-YCG** [comment]
每一个组件都会去开发自己的动效，因为目前只开发了浮层类组件的动效，所以其它组件继承了部分动画效果有待修改，可以优先下拉框等使用度高的动效开发
