### ISSUE TITLE
文本域必填没有显示红色提示框（不管聚不聚焦）

### ISSUE THREAD

**Issue by cmrong** [nomui/nomui#854]
必填红色提示框失效：看图片受理意见
![image](https://user-images.githubusercontent.com/34876116/175447419-25319b19-ae1d-41ef-8e86-c37c069143f9.png)

受影响分支：
![image](https://user-images.githubusercontent.com/34876116/175447553-9fbc2722-513d-4b78-a64e-5b5489f94e13.png)

**Comment by jieWangDevil** [comment]
我自己本地未重现和陈美容那边也无法重现此问题
