### ISSUE TITLE
GroupGrid新增一条明细

### ISSUE THREAD

**Issue by shenxiangxiong** [nomui/nomui#858]
在GroupGrid的第一次加载后点击添加按钮报错。
![WW$F 66X~ OK%ZQ`00 O$4S](https://user-images.githubusercontent.com/31055199/176107571-bc8777b3-ac04-4d0f-a4e8-fbddb7b645a3.png)

**Comment by fatalisa** [comment]
重复问题

**Comment by fatalisa** [comment]
#859
