### ISSUE TITLE
浏览器有滚动条的时候，定位错误

### ISSUE THREAD

**Issue by xiexingen** [nomui/nomui#93]
影响范围
所有的弹窗

![image](https://user-images.githubusercontent.com/7939085/106220650-ebcfd180-6216-11eb-87eb-c85d83686087.png)

**Comment by fatalisa** [comment]
layer的父元素为body的时候，不应该计算父元素的getBoundingClientRect()值，目前已解决，但是此方法如果在页面有iframe的时候可能还是会有问题，到时候才知道了。
